POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Helsinki-Turku raideyhteyden kehittämisestä apua suhdanteisiin ja kilpailukykyyn",
    "author": "Jarkko Heinonen",
    "url": "https://puheenvuoro.uusisuomi.fi/jarkko-heinonen/helsinki-turku-raideyhteyden-kehittamisesta-apua-suhdanteisiin-ja-kilpailukykyyn/",
    "likes": "0"
}