POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik11bW1vIiwiaWQiOiI1ZWYwYjFhYmQzZWFiNjIzYjhmNGU4MjYiLCJpYXQiOjE1OTI4ODcyNjR9.s8cFf8SL3lvgN3DJiNuLZcdab5jLKkSt94ZiwlAwJfs

{
    "title": "Dum dum blog from rest5",
    "author": "Robin Huumonen",
    "url": "www.eeeeee.fi/",
    "likes": "9000000000",
    "userId": "5ef0b1abd3eab623b8f4e826"
}