POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Suomen yhteisvastuut eurosta",
    "author": "Tuomas Malinen",
    "url": "https://puheenvuoro.uusisuomi.fi/tmalinen/suomen-yhteisvastuut-eurosta/",
    "likes": "19"
}