POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik11bW1vIiwiaWQiOiI1ZWYwYjFhYmQzZWFiNjIzYjhmNGU4MjYiLCJpYXQiOjE1OTMwMTA4MTN9.Pd39pAkpQeMD4oxKDIYfeR-ixLCS48eXpPzr8e9xPSw

{
    "title": "Mummon eka blogi",
    "author": "Mummo Ankka",
    "url": "www.ankkalinna.fi/",
    "likes": "333",
    "userId": "5ef0b1abd3eab623b8f4e826"
}